//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog_Table
    {
        public int BlogID { get; set; }
        public string Title { get; set; }
        public string Synopsis { get; set; }
        public string Content { get; set; }
        public string Image { get; set; }
        public System.DateTime DateTime { get; set; }
        public int View_number { get; set; }
        public int Like_number { get; set; }
        public int Comment_numbe { get; set; }
        public double Star { get; set; }
        public int Module { get; set; }
    }
}
